[package]
authors = ["Ben Wishovich <ben@benw.is>"]
categories = ["web-programming::http-server"]
description = "A rate-limiting middleware for Tower backed by the governor crate that allows configurable key based and global limits"
edition = "2021"
keywords = ["axum", "tower", "tonic", "rate-limit", "governor"]
license = "MIT OR Apache-2.0"
name = "tower_governor"
readme = "README.md"
repository = "https://github.com/benwis/tower-governor"
version = "0.4.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
forwarded-header-value = "0.1.1"
governor = "0.6.3"
http = "1.0.0"
pin-project = "1.0.12"
thiserror = "1.0.37"
tower = "0.4.13"
tracing = {version = "0.1.37", features = ["attributes"]}

axum = {version = "0.7", optional = true}

[dev-dependencies]
hyper = "1"
reqwest = {version = "0.12", default-features = false, features = ["json"]}
serde_json = "1.0.89"
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
tower = {version = "0.4", features = ["util"]}
tower-http = {version = "0.5", features = ["trace"]}
tracing-subscriber = {version = "0.3.16", features = ["env-filter"]}

[features]
default = ["axum"]
# Enables support for axum web framework
axum = ["dep:axum"]
# Enables tracing output for this middleware
tracing = []
